global:
  resolve_timeout: 5m


route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'fastapi_telegram'
  routes:
    - match:
        service: 'fastapi'
      receiver: 'fastapi_telegram'
    - match:
        service: 'rabbitmq'
      receiver: 'rabbitmq_telegram'


receivers:
- name: 'fastapi_telegram'
  telegram_configs:
  - bot_token: '<–¢–í–û–ô_–ë–û–¢_–¢–û–ö–ï–ù>'
    chat_id: '<–¢–í–û–ô_FASTAPI_CHAT_ID>'
    parse_mode: 'Markdown'
    message: |
      {{ if eq .CommonLabels.severity "critical" }}
      *üî• CRITICAL ALERT!*
      {{ else if eq .CommonLabels.severity "warning" }}
      *‚ö†Ô∏è WARNING!*
      {{ else }}
      *‚úÖ INFO*
      {{ end }}
      *Alert:* {{ .CommonLabels.alertname }}
      *Status:* {{ .CommonLabels.severity }}
      *Description:* {{ .CommonAnnotations.description }}
      *Instance:* {{ .CommonLabels.instance }}


- name: 'rabbitmq_telegram'
  telegram_configs:
  - bot_token: '<–¢–í–û–ô_–ë–û–¢_–¢–û–ö–ï–ù>'
    chat_id: '<–¢–í–û–ô_RABBITMQ_CHAT_ID>'
    parse_mode: 'Markdown'
    message: |
      {{ if eq .CommonLabels.severity "critical" }}
      *üî• CRITICAL ALERT!*
      {{ else if eq .CommonLabels.severity "warning" }}
      *‚ö†Ô∏è WARNING!*
      {{ else }}
      *‚úÖ INFO*
      {{ end }}
      *Alert:* {{ .CommonLabels.alertname }}
      *Status:* {{ .CommonLabels.severity }}
      *Description:* {{ .CommonAnnotations.description }}
      *Instance:* {{ .CommonLabels.instance }}

      